config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :recipes

      resources :ingredients

      resources :users

      resources :categories

      resources :dishes
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "dishes#index"
  resources :recipes
  resources :ingredients
  resources :users
  resources :categories
  resources :dishes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # Direct associations

  belongs_to :ingredient

  belongs_to :dish

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    ingredient.to_s
  end
end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < Api::V1::GraphitiController
  def index
    recipes = RecipeResource.all(params)
    respond_with(recipes)
  end

  def show
    recipe = RecipeResource.find(params)
    respond_with(recipe)
  end

  def create
    recipe = RecipeResource.build(params)

    if recipe.save
      render jsonapi: recipe, status: :created
    else
      render jsonapi_errors: recipe
    end
  end

  def update
    recipe = RecipeResource.find(params)

    if recipe.update_attributes
      render jsonapi: recipe
    else
      render jsonapi_errors: recipe
    end
  end

  def destroy
    recipe = RecipeResource.find(params)

    if recipe.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: recipe
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  def index
    @q = Recipe.ransack(params[:q])
    @recipes = @q.result(distinct: true).includes(:dish,
                                                  :ingredient).page(params[:page]).per(10)
  end

  def show; end

  def new
    @recipe = Recipe.new
  end

  def edit; end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      message = "Recipe was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @recipe, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: "Recipe was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    message = "Recipe was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to recipes_url, notice: message
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:ingredient_id, :quantity, :dish_id, :unit)
  end
end

app/views/recipes/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Recipe #<%= recipe.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Ingredient</dt>
      <dd>
        <% if @recipe.ingredient.present? %>
          <%= link_to recipe.ingredient, recipe.ingredient %>
        <% end %>
      </dd>

      <dt>Quantity</dt>
      <dd><%= recipe.quantity %></dd>

      <dt>Dish</dt>
      <dd>
        <% if @recipe.dish.present? %>
          <%= link_to recipe.dish, recipe.dish %>
        <% end %>
      </dd>

      <dt>Unit</dt>
      <dd><%= recipe.unit %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back recipe, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_recipe_url(recipe), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to recipe, method: :delete, data: { confirm: "Do you really want to delete this recipe?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(recipe.updated_at) %> ago
  </div>
</div>

app/views/recipes/_form.html.erb
<% was_validated = recipe.errors.any? %>

<%= form_with(model: recipe, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% ingredient_class = "form-control" %>
    <% ingredient_was_invalid = recipe.errors.include?(:ingredient) %>

    <% if was_validated %>
      <% if ingredient_was_invalid %>
        <% ingredient_class << " is-invalid" %>
      <% else %>
        <% ingredient_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :ingredient_id %>
    <%= f.collection_select :ingredient_id, Ingredient.all, :id, :to_s, {}, class: "form-control" %>
    <% if ingredient_was_invalid %>
      <% recipe.errors.full_messages_for(:ingredient).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% quantity_class = "form-control" %>
    <% quantity_was_invalid = recipe.errors.include?(:quantity) %>

    <% if was_validated %>
      <% if quantity_was_invalid %>
        <% quantity_class << " is-invalid" %>
      <% else %>
        <% quantity_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :quantity %>
    <%= f.text_field :quantity, class: quantity_class, placeholder: "Enter quantity" %>
    <% if quantity_was_invalid %>
      <% recipe.errors.full_messages_for(:quantity).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% dish_class = "form-control" %>
    <% dish_was_invalid = recipe.errors.include?(:dish) %>

    <% if was_validated %>
      <% if dish_was_invalid %>
        <% dish_class << " is-invalid" %>
      <% else %>
        <% dish_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :dish_id %>
    <%= f.collection_select :dish_id, Dish.all, :id, :to_s, {}, class: "form-control" %>
    <% if dish_was_invalid %>
      <% recipe.errors.full_messages_for(:dish).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% unit_class = "form-control" %>
    <% unit_was_invalid = recipe.errors.include?(:unit) %>

    <% if was_validated %>
      <% if unit_was_invalid %>
        <% unit_class << " is-invalid" %>
      <% else %>
        <% unit_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :unit %>
    <%= f.text_field :unit, class: unit_class, placeholder: "Enter unit" %>
    <% if unit_was_invalid %>
      <% recipe.errors.full_messages_for(:unit).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/recipes/_list_item.html.erb
<%= link_to recipe, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= recipe %>
    <small class="text-muted">
      <%= time_ago_in_words(recipe.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/recipes/_recipes_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "recipes_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :unit_cont, "Unit contains" %>
    <%= f.text_field :unit_cont, :class => "form-control", :placeholder => "Unit contains" %>
  </div>

  <div class="form-group">
    <%= f.label :quantity, "Quantity" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :quantity_gteq, :class => "form-control", :placeholder => "Quantity greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :quantity_lteq, :class => "form-control", :placeholder => "Quantity less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :dish_dish_name_cont, "Dish dish_name contains" %>
    <%= f.text_field :dish_dish_name_cont, :class => "form-control", :placeholder => "Dish dish_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :ingredient_ingredient_name_cont, "Ingredient ingredient_name contains" %>
    <%= f.text_field :ingredient_ingredient_name_cont, :class => "form-control", :placeholder => "Ingredient ingredient_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/recipes" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#recipes_filters">
  Show filters
</a>

app/views/recipes/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Recipe #<%= @recipe.id %>
      </h2>

      <div class="card-body">
        <%= render "form", recipe: @recipe %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Recipes

      <%= link_to new_recipe_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "recipes/recipes_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Recipes

        <%= link_to new_recipe_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @recipes, partial: "list_item", as: :recipe %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @recipes, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Recipe
      </h2>

      <div class="card-body">
        <%= render "form", recipe: @recipe %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @recipe, partial: "card", as: :recipe %>
  </div>
</div>