config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :recipes

      resources :ingredients

      resources :users

      resources :categories

      resources :dishes
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "dishes#index"
  resources :recipes
  resources :ingredients
  resources :users
  resources :categories
  resources :dishes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  # Direct associations

  has_many   :combinations,
             class_name: "Recipe",
             dependent: :nullify

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    ingredient_name
  end
end

app/controllers/api/v1/ingredients_controller.rb
class Api::V1::IngredientsController < Api::V1::GraphitiController
  def index
    ingredients = IngredientResource.all(params)
    respond_with(ingredients)
  end

  def show
    ingredient = IngredientResource.find(params)
    respond_with(ingredient)
  end

  def create
    ingredient = IngredientResource.build(params)

    if ingredient.save
      render jsonapi: ingredient, status: :created
    else
      render jsonapi_errors: ingredient
    end
  end

  def update
    ingredient = IngredientResource.find(params)

    if ingredient.update_attributes
      render jsonapi: ingredient
    else
      render jsonapi_errors: ingredient
    end
  end

  def destroy
    ingredient = IngredientResource.find(params)

    if ingredient.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: ingredient
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[show edit update destroy]

  def index
    @q = Ingredient.ransack(params[:q])
    @ingredients = @q.result(distinct: true).includes(:combinations).page(params[:page]).per(10)
  end

  def show
    @combination = Combination.new
  end

  def new
    @ingredient = Ingredient.new
  end

  def edit; end

  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      redirect_to @ingredient, notice: "Ingredient was successfully created."
    else
      render :new
    end
  end

  def update
    if @ingredient.update(ingredient_params)
      redirect_to @ingredient, notice: "Ingredient was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @ingredient.destroy
    redirect_to ingredients_url,
                notice: "Ingredient was successfully destroyed."
  end

  private

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:ingredient_name, :have_vs_not)
  end
end

app/views/ingredients/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Ingredient #<%= ingredient.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Ingredient name</dt>
      <dd><%= ingredient.ingredient_name %></dd>

      <dt>Have vs not</dt>
      <dd><%= ingredient.have_vs_not %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back ingredient, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_ingredient_url(ingredient), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to ingredient, method: :delete, data: { confirm: "Do you really want to delete this ingredient?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(ingredient.updated_at) %> ago
  </div>
</div>

app/views/ingredients/_form.html.erb
<% was_validated = ingredient.errors.any? %>

<%= form_with(model: ingredient, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% ingredient_name_class = "form-control" %>
    <% ingredient_name_was_invalid = ingredient.errors.include?(:ingredient_name) %>

    <% if was_validated %>
      <% if ingredient_name_was_invalid %>
        <% ingredient_name_class << " is-invalid" %>
      <% else %>
        <% ingredient_name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :ingredient_name %>
    <%= f.text_field :ingredient_name, class: ingredient_name_class, placeholder: "Enter ingredient name" %>
    <% if ingredient_name_was_invalid %>
      <% ingredient.errors.full_messages_for(:ingredient_name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-check">
    <% have_vs_not_class = "form-check-input" %>
    <% have_vs_not_was_invalid = ingredient.errors.include?(:have_vs_not) %>

    <% if was_validated %>
      <% if have_vs_not_was_invalid %>
        <% have_vs_not_class << " is-invalid" %>
      <% else %>
        <% have_vs_not_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :have_vs_not, class: "form-check-label" do %>
      <%= f.check_box :have_vs_not, class: have_vs_not_class %> Have vs not
    <% end %>
    <% if have_vs_not_was_invalid %>
      <% ingredient.errors.full_messages_for(:have_vs_not).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/ingredients/_ingredient_combinations.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Combinations

    <a data-toggle="collapse" href="#ingredient_combinations_new_form">
      Add recipe
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @ingredient.combinations.each do |recipe| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to recipe, recipe %>

        <%= link_to recipe, method: :delete, data: { confirm: "Do you really want to delete this recipe" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="ingredient_combinations_new_form">
        <%= render partial: "ingredients/ingredient_combinations_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/ingredients/_ingredient_combinations_new_form.html.erb
<%= form_with(model: @combination, local: true) do |f| %>

  <%= f.hidden_field :ingredient_id, value: @ingredient.id %>

  <div class="form-group">
    <%= f.label :quantity %>

    <%= f.text_field :quantity, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :measure %>

    <%= f.text_field :measure, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :dish_id %>

    <%= f.collection_select :dish_id, Dish.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Create combination", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/ingredients/_ingredients_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "ingredients_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :ingredient_name_cont, "Ingredient name contains" %>
    <%= f.text_field :ingredient_name_cont, :class => "form-control", :placeholder => "Ingredient name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :have_vs_not_eq, "Have vs not" %>
    <div>
      <label class="radio-inline">
        <%= f.radio_button :have_vs_not_eq, "1", checked: ((params[:q] && params[:q][:have_vs_not_eq]) == "1" ? "checked" : "") %> Yes
      </label>
      <label class="radio-inline">
        <%= f.radio_button :have_vs_not_eq, "0", checked: ((params[:q] && params[:q][:have_vs_not_eq]) == "0" ? "checked" : "")%> No
      </label>
      <label class="radio-inline">
        <%= f.radio_button :have_vs_not_eq, ""%> Either
      </label>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>




  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/ingredients" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#ingredients_filters">
  Show filters
</a>

app/views/ingredients/_list_item.html.erb
<%= link_to ingredient, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= ingredient %>
    <small class="text-muted">
      <%= time_ago_in_words(ingredient.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/ingredients/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Ingredient #<%= @ingredient.id %>
      </h2>

      <div class="card-body">
        <%= render "form", ingredient: @ingredient %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/ingredients/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Ingredients

      <%= link_to new_ingredient_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "ingredients/ingredients_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Ingredients

        <%= link_to new_ingredient_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @ingredients, partial: "list_item", as: :ingredient %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @ingredients, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/ingredients/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Ingredient
      </h2>

      <div class="card-body">
        <%= render "form", ingredient: @ingredient %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/ingredients/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @ingredient, partial: "card", as: :ingredient %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "ingredients/ingredient_combinations" %>
  </div>
</div>